### ISSUE TITLE
feature: add scalePolicy in lws

### ISSUE THREAD

**Issue by googs1025** [kubernetes-sigs/lws#213]
**What would you like to be added**:
I want to implement a function similar to scalePolicy, the api is as follows. 
```yaml
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: leaderworkerset-sample
spec:
  scalePolicy:
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80
  replicas: 3
  leaderWorkerTemplate:
    size: 4
    workerTemplate:
      spec:
        containers:
        - name: nginx
          image: nginx:1.14.2
          resources:
            limits:
              cpu: "100m"
            requests:
              cpu: "50m"
          ports:
          - containerPort: 8080
```
We can implement the scale subresource (it seems to have been implemented now) and embed HPA, so that users can use scalePolicy directly without using HPA separately.

This would involve an api-change, I'll contribute a KEP if needed.

**Why is this needed**:
- users can use scalePolicy directly without using HPA separately.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.
