### ISSUE TITLE
Set RANK environment variables for pods

### ISSUE THREAD

**Issue by hwdef** [kubernetes-sigs/lws#368]
**What would you like to be added**:

Set rank environment variables for pods

**Why is this needed**:

Some inference frameworks require rank numbers when running distributedly, such as sglang

**Completion requirements**:

When creating a pod, set a RANK environment variable for each pod, and the value of the environment variable is the same as `leaderworkerset.sigs.k8s.io/worker-index`

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by yankay** [comment]
We can obtain the index by using the Kubernetes [Downward API](https://kubernetes.io/docs/concepts/workloads/pods/downward-api/) to pass the Pod's label as an environment variable to the container:

```
env:
  - name: INDEX
    valueFrom:
      fieldRef:
        fieldPath: metadata.labels['leaderworkerset.sigs.k8s.io/worker-index']
```
