### ISSUE TITLE
LWS RollingUpdate support in-place update for image

### ISSUE THREAD

**Issue by zmberg** [kubernetes-sigs/lws#376]
**What would you like to be added**:
I'd like lws to add a field to support in-place upgrades against Image, rather than rebuilding the Pod.  As follows:
```yaml
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: vllm
spec:
  rolloutStrategy:
    type: RollingUpdate
    rollingUpdateConfiguration:
      podUpdatePolicy: InPlaceIfPossible | ReCreate
```
- ReCreate indicates that we always delete Pod and create new Pod during Pod update, which is the default behavior.
- InPlaceIfPossible indicates that we try to in-place update Pod instead of recreating Pod when possible. Currently, only image update of pod spec is allowed. Any other changes to the pod spec will fall back to ReCreate where pod will be recreated.

**Why is this needed**:
Rolling upgrades that rebuild the Pod every time cause the following problems:
1. The model data is too large and it takes too long to load the data.
2. GPU is a scarce resource, which is easily occupied by other Pods after it is released during the rolling upgrade process.

**Completion requirements**:
LWS essentially uses a community StatefulSet to manage Pods. [OpenKruise](https://openkruise.io/) as a CNCF incubating project has a very broad user base in the community, and it provides an [Advanced StatefulSet](https://openkruise.io/docs/user-manuals/advancedstatefulset) that supports In-place update image capability. If LWS can consider interfacing with OpenKruise Advanced StatefulSet, it can support this feature at a relatively small cost.

Currently there are some companies with similar requirements, such as xiaohongshu, if you agree with this solution, I can contribute code.

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.
