### ISSUE TITLE
Create a new lws or modify replicas, UpdateInProgress will also exist in conditions

### ISSUE THREAD

**Issue by JesseStutler** [kubernetes-sigs/lws#400]
**What happened**:
I am adapting lws in volcano, and when adapting the rolling update scenario, I determine whether an lws is in a rolling update based on the presence of an UpdateInProgress condition set to True in the lws. However, now when I create a new lws, I find that sometimes the UpdateInProgress condition is also stably generated, which does not match the description of this condition:
```
// LeaderWorkerSetUpdateInProgress means lws is performing a rolling update. UpdateInProgress
// is true when the lws is in upgrade process after the (leader/worker) template is updated. If only replicas is modified, it will
// not be considered as UpdateInProgress.
LeaderWorkerSetUpdateInProgress LeaderWorkerSetConditionType = "UpdateInProgress"
```
When creating a new lws or modifying replicas, this condition should not occur, but currently I can basically reproduce this situation, especially repeatedly creating and deleting the same lws should be able to stably reproduce it

**What you expected to happen**:
When creating a new lws or modifying replicas, this condition should not occur

**How to reproduce it (as minimally and precisely as possible)**:
My lws yaml:
```
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: leaderworkerset-rollout
spec:
  rolloutStrategy:
    type: RollingUpdate
    rollingUpdateConfiguration:
      maxSurge: 2
  replicas: 4
  leaderWorkerTemplate:
    size: 4
    workerTemplate:
      metadata:
        name: worker    
      spec:
        containers:
        - name: nginx
          image: nginx:1.14.2
          resources:
            limits:
              cpu: "100m"
            requests:
              cpu: "50m"
          ports:
          - containerPort: 8080
```

**Anything else we need to know?**:
Especially repeatedly creating and deleting the same lws should be able to stably reproduce it

**Environment**:

- Kubernetes version (use `kubectl version`): v1.31
- LWS version (use `git describe --tags --dirty --always`): v0.5.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
