### ISSUE TITLE
How can I use the NetworkConfig feature when using the v0.3 version of the SDK?

### ISSUE THREAD

**Issue by Mr-lixh** [kubernetes-sigs/lws#405]
Due to some historical reasons, our project can only use the v0.3 version of the SDK, but I need the UniquePerReplica subdomainPolicy. What should I do?

Can I add the lws annotation leaderworkerset.sigs.k8s.io/subdomainPolicy to extend this feature in lws_webhook?

```yaml
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: helloworld
  annotations:
    # The lws_webhook adjusts the NetworkConfig configuration through this annotation.
    leaderworkerset.sigs.k8s.io/subdomainPolicy: UniquePerReplica
```
