### ISSUE TITLE
There is recursive deployment？why？

### ISSUE THREAD

**Issue by SimpleMonitor** [kubernetes-sigs/lws#435]
The expected 1 leader + 3 workers, a total of 4 Pods, have all been successful so far. But why are they distributed in different deployments and there are a lot of such recursive deployments?

![Image](https://github.com/user-attachments/assets/f0385b33-9ad6-4d30-9a03-ad7aae77aa35)

My lws yaml:

```
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: vllm
  namespace: lws-vllm   
spec:
  replicas: 1
  leaderWorkerTemplate:
    size: 4
    restartPolicy: RecreateGroupOnPodRestart
    leaderTemplate:
      metadata:          
        labels:
          role: leader
      spec:     
        nodeSelector: 
          gpu: v100
        imagePullSecrets:
        - name: qcloud-registry-secret          
        containers:
        - name: vllm-leader
          image: ccr.ccs.tencentyun.com/imroc/vllm-lws:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: RAY_CLUSTER_SIZE
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['leaderworkerset.sigs.k8s.io/size']
          command:
          - sh
          - -c
          - |
            /vllm-workspace/ray_init.sh leader --ray_cluster_size=$RAY_CLUSTER_SIZE
            python3 -m vllm.entrypoints.openai.api_server \
              --port 8080 \
              --model /data/DeepSeek-R1-Distill-Qwen-32B \
              --served-model-name deepseek_r1 \
              --tensor-parallel-size 2 \
              --pipeline-parallel-size 4 \
              --enforce-eager \
              --trust-remote-code \
              --max-model-len 10000 \
              --gpu_memory_utilization 0.8 \
              --dtype float16 \
              --enable-reasoning \
              --reasoning-parser deepseek_r1
          resources:
            limits:
              nvidia.com/gpu: "2"
          ports:
          - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /data/DeepSeek-R1-Distill-Qwen-32B
            name: nfs
        volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 15Gi
        - name: nfs
          nfs:
            server: xx.xx.xx.xx
            path: /models/LLM/DeepSeek-R1-Distill-Qwen-32B
            readOnly: true            
    workerTemplate:
      metadata:
        namespace: lws-vllm          
      spec:
        nodeSelector: 
          gpu: v100
        imagePullSecrets:
        - name: qcloud-registry-secret           
        containers:
        - name: vllm-worker
          image: ccr.ccs.tencentyun.com/imroc/vllm-lws:latest
          imagePullPolicy: IfNotPresent
          command:
          - sh
          - -c
          - "/vllm-workspace/ray_init.sh worker --ray_address=$(LWS_LEADER_ADDRESS)"
          resources:
            limits:
              nvidia.com/gpu: "2"
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /data/DeepSeek-R1-Distill-Qwen-32B
            name: nfs
        volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 15Gi
        - name: nfs
          nfs:
            server: xx.xx.xx.xx
            path: /models/LLM/DeepSeek-R1-Distill-Qwen-32B
            readOnly: true 
---

apiVersion: v1
kind: Service
metadata:
  name: vllm-api
  namespace: lws-vllm   
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    leaderworkerset.sigs.k8s.io/name: vllm
    role: leader
  type: ClusterIP
``` 

Environment:

- Kubernetes version :Master v1.26.1
- LWS version: v0.5.1
