### ISSUE TITLE
Unexpected restarts of lws controller

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/lws#48]
**What happened**:

From the kubectl output, lws controller restarts for several times, this should not happen.
```
NAME                                                    READY   STATUS    RESTARTS        AGE
leader-worker-set-controller-manager-79fdd9c6cc-fr8q2   2/2     Running   7 (7m52s ago)   23h
```

**What you expected to happen**:

No restarts.

**How to reproduce it (as minimally and precisely as possible)**:

I didn't collect the logs yet.

**Anything else we need to know?**:

```
containerStatuses:
  - containerID: containerd://1b5b32225eaf8f914d033cf2cb4472888a5da2a786b2ca62675abade155c6b1b
    image: gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0
    imageID: sha256:7ebda747308b686ef6471bd8377085bce9f210baef15ce2a9bb6c5d8ccd773dc
    lastState:
      terminated:
        containerID: containerd://2c14c20f6a3cc70caff6c8a550c44f6ae60c16c441277f6e18414a0d631a3b26
        exitCode: 255
        finishedAt: "2024-03-09T02:35:18Z"
        reason: Unknown
        startedAt: "2024-03-08T03:10:25Z"
    name: kube-rbac-proxy
    ready: true
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2024-03-09T02:35:37Z"
  - containerID: containerd://f3a839d4862cc4ca7b60b00919f73a69193def25ffab1d89ff0aaa0ea3cbf476
    image: registry.cn-shanghai.aliyuncs.com/kerthcet-public/lws:466f36b-dirty
    imageID: registry.cn-shanghai.aliyuncs.com/kerthcet-public/lws@sha256:b9f6a95f33ef7be485cf95da878cf24db1a18fa6e23dcc47e767f2297ec26dc7
    lastState:
      terminated:
        containerID: containerd://46effa439479d6136bbb1a38cb242556fd9cd267283357dee3775670d0cbb004
        exitCode: 1
        finishedAt: "2024-03-11T01:04:37Z"
        reason: Error
        startedAt: "2024-03-10T23:57:47Z"
    name: manager
    ready: true
    restartCount: 90
    started: true
    state:
      running:
        startedAt: "2024-03-11T01:04:45Z"
```

**Environment**:

- Kubernetes version (use `kubectl version`):
- LWS version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
