### ISSUE TITLE
ErrImageNeverPull in worker

### ISSUE THREAD

**Issue by jli113** [kubernetes-sigs/lws#495]
**What happened**: Error from server (BadRequest): container "sglang-worker" in pod "sglang-0-1" is waiting to start: ErrImageNeverPull

**What you expected to happen**: imagePullPolicy: Never

**How to reproduce it (as minimally and precisely as possible)**: set imagePullPolicy: Never in workerTemplate

**Anything else we need to know?**: microk8s cluster using local image, lws file is here 

```
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: sglang
spec:
  replicas: 1
  leaderWorkerTemplate:
    size: 2
    restartPolicy: RecreateGroupOnPodRestart
    leaderTemplate:
      metadata:
        labels:
          role: leader
      spec:
        containers:
          - name: sglang-leader
            image: docker.io/library/sglang:local
            imagePullPolicy: Never
            command:
              - bash
              - -c
              - |
                set -x
                exec python3 -m sglang.launch_server \
                  --model-path /root/.cache/models/QwQ-32B \
                  --served-model-name QwQ-32B \
                  --nnodes $LWS_GROUP_SIZE \
                  --tp 2 \
                  --node-rank 0 \
                  --dist-init-addr $(LWS_LEADER_ADDRESS):5000 \
                  --trust-remote-code \
                  --host 0.0.0.0 \
                  --port 30000
            resources:
              limits:
                nvidia.com/gpu: "1"
            ports:
              - containerPort: 30000
            volumeMounts:
              - mountPath: /dev/shm
                name: dshm
              - mountPath: /root/.cache/models
                name: model
        volumes:
          - name: dshm
            emptyDir:
              medium: Memory
              sizeLimit: 40Gi
          - name: model
            hostPath:
              path: /home/k1/model
    workerTemplate:
      spec:
        containers:
          - name: sglang-worker
            image: docker.io/library/sglang:local
            imagePullPolicy: Never
            command:
              - bash
              - -c
              - |
                set -x
                exec python3 -m sglang.launch_server \
                  --model-path /root/.cache/models/QwQ-32B \
                  --served-model-name QwQ-32B \
                  --nnodes $LWS_GROUP_SIZE \
                  --tp 2 \
                  --node-rank $ORDINAL_NUMBER \
                  --dist-init-addr $(LWS_LEADER_ADDRESS):5000 \
                  --trust-remote-code
            resources:
              limits:
                nvidia.com/gpu: "1"
            volumeMounts:
              - mountPath: /dev/shm
                name: dshm
              - mountPath: /root/.cache/models
                name: model
        volumes:
          - name: dshm
            emptyDir:
              medium: Memory
              sizeLimit: 40Gi
          - name: model
            hostPath:
              path: /home/k1/model

```

**Environment**:  microk8s

- Kubernetes version (use `kubectl version`):

Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.32.3

- LWS version (use `git describe --tags --dirty --always`): 0.6.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
PRETTY_NAME="Ubuntu 24.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.2 LTS (Noble Numbat)"
VERSION_CODENAME=noble

- Kernel (e.g. `uname -a`):
Linux k2 6.11.0-21-generic #21~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Feb 24 16:52:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
