### ISSUE TITLE
exclusive-topology  antiAffinity should include matching LWS name

### ISSUE THREAD

**Issue by panpan0000** [kubernetes-sigs/lws#539]
**What happened**:

should add below 
```
          - key: leaderworkerset.sigs.k8s.io/group-key
            operator: In
            values:
            - $MY_LWS_NAME
```

**What you expected to happen**:

the whole worker affinity looks like 

```
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: leaderworkerset.sigs.k8s.io/group-key
            operator: In
            values:
            - $MY_LWS_NAME
          - key: leaderworkerset.sigs.k8s.io/group-key
            operator: Exists
          - key: leaderworkerset.sigs.k8s.io/group-key
            operator: NotIn
            values:
            - 8fb.....23d207e113
        topologyKey: topology.kubernetes.io/zone
```

**How to reproduce it (as minimally and precisely as possible)**:

in the same namespace:

1. run a LWS(named "A" ) with `leaderworkerset.sigs.k8s.io/exclusive-topology` annotation.
2. run another LWS(named "B" ) with `leaderworkerset.sigs.k8s.io/exclusive-topology` annotation.
you will see B will be pending due to A already live in those nodes (but B may use diff resource than A, they should not compete and A should not stop B from running )

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
- LWS version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
