### ISSUE TITLE
RollingUpdate stuck if all old pod are not ready

### ISSUE THREAD

**Issue by gujingit** [kubernetes-sigs/lws#567]
**What happened**:
Rolling update stuck if all old pod were not ready.

**What you expected to happen**:

Rolling update successfully.

**How to reproduce it (as minimally and precisely as possible)**:

old.yaml
```yaml
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: leaderworkerset-rollout
spec:
  rolloutStrategy:
    type: RollingUpdate
    rollingUpdateConfiguration:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 4
  leaderWorkerTemplate:
    size: 1
    workerTemplate:
      spec:
        containers:
          - name: nginx
            image: image-not-exist:v1
            ports:
              - containerPort: 8080
```
new.yaml
```yaml
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: leaderworkerset-rollout
spec:
  rolloutStrategy:
    type: RollingUpdate
    rollingUpdateConfiguration:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 4
  leaderWorkerTemplate:
    size: 1
    workerTemplate:
      spec:
        containers:
          - name: nginx
            image: nginx:latest
            ports:
              - containerPort: 8080
```
 
```
kubectl get po

NAME                        READY   STATUS         RESTARTS   AGE
leaderworkerset-rollout-0   0/1     ErrImagePull   0          42s
leaderworkerset-rollout-1   0/1     ErrImagePull   0          42s
leaderworkerset-rollout-2   0/1     ErrImagePull   0          42s
leaderworkerset-rollout-3   0/1     ErrImagePull   0          42s
leaderworkerset-rollout-4   1/1     Running        0          22s

```

**Anything else we need to know?**:

v0.6.2 works well,  but fails on the main branch .

**Environment**:

- Kubernetes version (use `kubectl version`):
Client Version: v1.32.1
Kustomize Version: v5.5.0
Server Version: v1.33.1-aliyun.1

- LWS version (use `git describe --tags --dirty --always`):
v0.6.1-29-gf9a6396-dirty

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
