### ISSUE TITLE
Unify the API for single-node-serving vs cross-node-serving

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/lws#9]
/kind feature

Can we unify the single-node-serving and multi-node-serving with this API together, in singe-node-serving, the worker is 1. Then for upstream application no need to switch from different workloads(deployment vs leaderworkerSet), 
However we may have to change our design, IIUC the leader is default to 1.

Or we're more dedicated?

**Comment by ahg-g** [comment]
Single-host should work with the current design, the replicas of the service basically be the leaders. Setting the size=1 means the group size is 1, which is single host.

**Comment by kerthcet** [comment]
Ok I'll have a look at the controller design and decide whether to close this issue or not.

**Comment by kerthcet** [comment]
Seems yes with this yaml
```
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  labels:
    app.kubernetes.io/name: leaderworkerset
    app.kubernetes.io/instance: leaderworkerset-sample
    app.kubernetes.io/part-of: leader-worker-set
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: leader-worker-set
  name: leaderworkerset-sample
spec:
  replicas: 3
  leaderWorkerTemplate:
    size: 1
    restartPolicy: RecreateGroupOnPodRestart
    workerTemplate:
      spec:
        containers:
        - name: nginx
          image: nginx:1.14.2
          resources:
            limits:
              cpu: "100m"
            requests:
              cpu: "50m"
          ports:
          - containerPort: 8080

```
